import type { NextPage } from 'next'
import Head from 'next/head'
// TailWindCSSをインポート
import 'tailwindcss/tailwind.css'
// import styles from '../styles/Home.module.css'

// ApolloClientが提供するuseQuery Hookを利用することでデータの取得状態やエラー情報を取得する
import { gql, useQuery } from '@apollo/client';

// GraphQLのクエリを定義
const GET_USERS = gql`
    query GetUsers {
        users {
            id
            name
            email
        }
    }
`;

const Home: NextPage = () => {
    // useQuery Hookを利用してクエリを実行し、接続状態とデータを取得
    const { data, loading, error } = useQuery(GET_USERS);

    if (loading) return <p>Now Loading...</p>;
    if (error) return <p>Error: {error.message}</p>;

    const { users } = data;
    
    return (
        <div className='container'>
            <Head>
                <title>GraphQL-Prisma-SupabaseDB</title>
                <meta name="description" content="Generated by create-next-app" />
                <link rel="icon" href="../favicon.ico" />
            </Head>

            <main className='text-center'>
                <h1 className="mt-5 text-3xl font-bold text-green-700">GraphQL-Prisma-Supabase(Postgres)</h1>
                <h2 className="mt-3 text-xl font-semibold text-slate-500">GraphQL & DB接続 & TailWind CSSお試し</h2>
                <h3 className="mt-5 text-2xl font-semibold underline">ユーザ情報</h3>
                {users.map((user: { id: number, name: string; email: string }) => (
                    <ul className='list-disc list-inside' key={user.id}>
                        <li className="mt-5 text-medium">
                            <span className='mr-5'>Name: {user.name}</span>
                            <span className='text-blue-700'>Email: {user.email}</span>
                        </li>
                    </ul>
                ))}
            </main>
        </div>
    );
};

export default Home;